modLoader = "javafml"
loaderVersion = "[${forgeMajorVersion},)"
issueTrackerURL = "https://github.com/creep3rcrafter//issues"
license = "All Rights Reserved"

[[mods]]
modId = "projectiles"
version = "${version}"
displayName = "Projectiles (Forge)"
displayURL = ""
authors = "Creep3rCrafter"
description = ''''''
logoFile = "logo.png"

[[dependencies.projectiles]]
modId = "forge"
mandatory = true
versionRange = "[${forgeMajorVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectiles]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectiles]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "AFTER"
side = "BOTH"